<?
class anti_mat extends e_anti_mat{}
class cache extends e_cache{}
class client_section extends e_client_section{}
class db extends e_db{}
class div_into_pages extends e_div_into_pages{}
class error extends e_error{}
class fb extends e_fb{}
class garbage extends e_garbage{}
class message extends e_message{}
class module extends e_module{}
class permissions extends e_permissions{}
class sections extends e_sections{}
class sendmail extends e_sendmail{}
class spider extends e_spider{}
class stat extends e_stat{}
class sys_control extends e_sys_control{}
class utils extends e_utils{}
class xml extends e_xml{}
class sys_control_ajax extends e_sys_control_ajax{}